### ISSUE TITLE
Unable to load asset: "assets//atlasMap.png".

### ISSUE THREAD

**Issue by Ensonberg** [Yayo-Arellano/flutter_games_compilation#1]
Thanks for building this out , but I am having issues running it on my mobile phone
E/flutter (10579): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets//atlasMap.png".
E/flutter (10579): The asset does not exist or has empty data.
E/flutter (10579): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:328:9)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #1      Images._fetchToMemory (package:flame/src/cache/images.dart:163:18)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #2      _TextureAtlasData._load (package:flame_gdx_texture_packer/atlas/texture_atlas.dart:78:26)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #3      TextureAtlas.load (package:flame_gdx_texture_packer/atlas/texture_atlas.dart:44:23)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #4      Assets.load (package:new_super_jumper/assets.dart:61:19)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #5      main (package:new_super_jumper/main.dart:16:3)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): 
E/flutter (10579): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets//atlasMap.png".
E/flutter (10579): The asset does not exist or has empty data.
E/flutter (10579): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:328:9)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #1      Images._fetchToMemory (package:flame/src/cache/images.dart:163:18)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #2      _TextureAtlasData._load (package:flame_gdx_texture_packer/atlas/texture_atlas.dart:78:26)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #3      TextureAtlas.load (package:flame_gdx_texture_packer/atlas/texture_atlas.dart:44:23)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #4      Assets.load (package:new_super_jumper/assets.dart:61:19)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579): #5      main (package:new_super_jumper/main.dart:16:3)
E/flutter (10579): <asynchronous suspension>
E/flutter (10579):

**Comment by Yayo-Arellano** [comment]
It has been [fixed](https://github.com/Yayo-Arellano/flutter_games_compilation/commit/1568b5a991ee1c26a376557c77c5b47d360fd9a6) in the latest version. Please try again.
