### ISSUE TITLE
cant run jumper

### ISSUE THREAD

**Issue by wengxianxun** [Yayo-Arellano/flutter_games_compilation#2]
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:22:15: Error: The type 'World/*1*/' of the field 'Forge2DGame.world' is not a subtype of the type 'World/*2*/' of the inherited setter 'FlameGame.world'.
 - 'World/*1*/' is from 'package:forge2d/src/dynamics/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/forge2d-0.11.0/lib/src/dynamics/world.dart').
 - 'World/*2*/' is from 'package:flame/src/camera/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/world.dart').
  final World world;
              ^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/flame_game.dart:54:7: Context: This is the declaration of the setter 'FlameGame.world'.
  set world(W newWorld) {
      ^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:22:15: Error: The return type of the method 'Forge2DGame.world' is 'World/*1*/', which does not match the return type, 'World/*2*/', of the overridden method, 'FlameGame.world'.
 - 'World/*1*/' is from 'package:forge2d/src/dynamics/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/forge2d-0.11.0/lib/src/dynamics/world.dart').
 - 'World/*2*/' is from 'package:flame/src/camera/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/world.dart').
Change to a subtype of 'World/*2*/'.
  final World world;
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/flame_game.dart:53:9: Context: This is the overridden method ('world').
  W get world => _world;
        ^
lib/my_game.dart:31:7: Error: Class 'Forge2DGame with HasKeyboardHandlerComponents<World>' inherits multiple members named 'world' with incompatible signatures.
Try adding a declaration of 'world' to 'Forge2DGame with HasKeyboardHandlerComponents<World>'.
class MyGame extends Forge2DGame
      ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:22:15: Context: This is one of the overridden members.
  final World world;
              ^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/flame_game.dart:53:9: Context: This is one of the overridden members.
  W get world => _world;
        ^^^^^
lib/my_game.dart:31:7: Error: The type 'World/*1*/' of the inherited field 'Forge2DGame.world' is not a subtype of the type 'World/*2*/' of the inherited setter 'FlameGame.world'.
 - 'World/*1*/' is from 'package:forge2d/src/dynamics/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/forge2d-0.11.0/lib/src/dynamics/world.dart').
 - 'World/*2*/' is from 'package:flame/src/camera/world.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/world.dart').
class MyGame extends Forge2DGame
      ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:22:15: Context: This is the declaration of the field 'Forge2DGame.world'.
  final World world;
              ^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/flame_game.dart:54:7: Context: This is the declaration of the setter 'FlameGame.world'.
  set world(W newWorld) {
      ^^^^^
lib/my_game.dart:47:23: Error: A value of type 'FixedResolutionViewport' can't be assigned to a variable of type 'Viewport'.
 - 'FixedResolutionViewport' is from 'package:flame/src/game/camera/viewport.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/camera/viewport.dart').
 - 'Viewport' is from 'package:flame/src/camera/viewport.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/viewport.dart').
    camera.viewport = FixedResolutionViewport(screenSize);
                      ^
lib/my_game.dart:68:12: Error: The method 'followBodyComponent' isn't defined for the class 'CameraComponent'.
 - 'CameraComponent' is from 'package:flame/src/camera/camera_component.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/camera_component.dart').
Try correcting the name to the name of an existing method, or defining a method named 'followBodyComponent'.
    camera.followBodyComponent(hero, worldBounds: worldBounds);
           ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/body_component.dart:51:32: Error: A value of type 'CameraComponent' can't be returned from a function with return type 'Camera'.
 - 'CameraComponent' is from 'package:flame/src/camera/camera_component.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/camera_component.dart').
 - 'Camera' is from 'package:flame/src/game/camera/camera.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/camera/camera.dart').
  Camera get camera => gameRef.camera;
                               ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:12:30: Error: The argument type 'Camera' can't be assigned to the parameter type 'CameraComponent?'.
 - 'Camera' is from 'package:flame/src/game/camera/camera.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/game/camera/camera.dart').
 - 'CameraComponent' is from 'package:flame/src/camera/camera_component.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/camera_component.dart').
        super(camera: camera ?? Camera()) {
                             ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flame_forge2d-0.14.1+1/lib/forge2d_game.dart:14:17: Error: The setter 'zoom' isn't defined for the class 'CameraComponent'.
 - 'CameraComponent' is from 'package:flame/src/camera/camera_component.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/flame-1.9.1/lib/src/camera/camera_component.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'zoom'.
    this.camera.zoom = zoom;
                ^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/wengxianxun/fvm/versions/stable/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/wengxianxun/fvm/versions/stable/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Yayo-Arellano** [comment]
I updated to the latest version of Flame. Now it should work as expected
